# Generated by Django 4.2.5 on 2023-09-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwabookmark",
            name="is_template",
            field=models.BooleanField(default=False, verbose_name="Is template"),
        ),
    ]
