# Generated by Django 4.2.5 on 2023-09-22 08:52

from django.db import migrations, models
import djmanhwabookmarks.validators


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0003_manhwabookmark_chapter_images_selector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwabookmark",
            name="chapter_image_attribute",
            field=models.CharField(
                blank=True,
                default="src",
                max_length=255,
                verbose_name="Chapter image attribute",
            ),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="chapter_images_selector",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[djmanhwabookmarks.validators.validate_selector_syntax],
                verbose_name="Chapter images selector",
            ),
        ),
    ]
