# Generated by Django 4.2.5 on 2023-11-12 06:08
from typing import cast
from django.db import migrations, models


def fix_priority_field(apps, schema_editor):
    Model = cast(type[models.Model], apps.get_model('djmanhwabookmarks', 'ManhwaBookmark'))
    for bookmark in Model.objects.all():
        bookmark.priority = 0 if bookmark.next_chapter_url is None else bookmark.priority_multiplier  # type: ignore
        bookmark.save()


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0004_manhwabookmark_chapter_image_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwabookmark",
            name="priority",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Priority"
            ),
        ),
        migrations.AddField(
            model_name="manhwabookmark",
            name="priority_multiplier",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Priority multiplier"
            ),
        ),
        migrations.RunPython(fix_priority_field, lambda *args: None),
    ]
