# Generated by Django 4.2.5 on 2023-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0006_alter_manhwabookmark_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwabookmark",
            name="chapter_url",
            field=models.URLField(
                max_length=1000, unique=True, verbose_name="Chapter url"
            ),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="next_chapter_url",
            field=models.URLField(
                blank=True,
                editable=False,
                max_length=1000,
                null=True,
                unique=True,
                verbose_name="Next chapter url",
            ),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="url",
            field=models.URLField(
                blank=True,
                editable=False,
                max_length=1000,
                null=True,
                unique=True,
                verbose_name="Url",
            ),
        ),
    ]
