# Generated by Django 4.2.5 on 2023-11-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0007_alter_manhwabookmark_chapter_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwabookmark",
            name="extractor_type",
            field=models.CharField(
                choices=[("mechanical_soup", "MechanicalSoup")],
                default="mechanical_soup",
                max_length=100,
                verbose_name="Extractor type",
            ),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="chapter_images_selector",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Chapter images selector"
            ),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="chapter_number_regex",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="chapter_number_selector",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="description_selector",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="next_chapter_url_selector",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="title_selector",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="manhwabookmark",
            name="url_selector",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
