# Generated by Django 4.2.7 on 2023-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0008_manhwabookmark_extractor_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manhwabookmark",
            name="extractor_type",
            field=models.CharField(
                choices=[
                    ("mechanical_soup", "MechanicalSoup"),
                    ("playwright", "Playwright"),
                ],
                default="mechanical_soup",
                max_length=100,
                verbose_name="Extractor type",
            ),
        ),
    ]
