# Generated by Django 4.2.7 on 2024-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djmanhwabookmarks", "0009_alter_manhwabookmark_extractor_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="manhwabookmark",
            name="excluded_next_chapter_selector",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Excluded next chapter selector",
            ),
        ),
    ]
