# Generated by Django 5.1.3 on 2025-11-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djmanhwabookmarks', '0010_manhwabookmark_excluded_next_chapter_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manhwabookmark',
            name='next_chapter_url_selector',
            field=models.CharField(blank=True, max_length=255, verbose_name='Next chapter url'),
        ),
        migrations.AlterField(
            model_name='manhwabookmark',
            name='title',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Title'),
        ),
    ]
